const questions=[
{section:'WHO ARE YOU?',q:'What matters most to you when connecting with other people?',o:['Building genuine relationships','Sharing ideas and experiences','Finding opportunities','Working together toward common goals'],m:[{Builder:1,Connector:2},{Visionary:2,Connector:1},{Entrepreneur:2,Connector:1},{Community:1,Builder:2}]},
{section:'WHO ARE YOU?',q:'How do you naturally contribute to a community?',o:['I come up with ideas','I help people get things done','I share knowledge and resources','I connect people with one another','I’m more of a supporter or cheerleader'],m:[{Visionary:3},{Builder:3},{Community:2,Builder:1},{Connector:3},{Community:3}]},
{section:'WHO ARE YOU?',q:'Which best describes what you’re looking for right now?',o:['New opportunities','New connections','A way to turn an idea into reality','A community where I belong','Ways to make a difference'],m:[{Entrepreneur:2},{Connector:2},{Visionary:1,Builder:2},{Community:3},{Community:2,Builder:1}]},
{section:'WHAT DO YOU WANT?',q:'What do you think is missing most from online communities today?',o:['Authentic connections','Trustworthy information','Opportunities to collaborate','A place where ideas can become action','Communities that actually accomplish things'],m:[{Connector:2},{Community:2},{Connector:1,Builder:1},{Visionary:1,Builder:2},{Community:2,Builder:1}]},
{section:'WHAT DO YOU WANT?',q:'What would you most like MagaCircle™ to help you accomplish?',o:['Meaningful connections','Business opportunities','Knowledge and resources','Collaboration on projects','A platform to share my ideas'],m:[{Connector:3},{Entrepreneur:3},{Community:2},{Builder:2,Connector:1},{Visionary:3}]},
{section:'WHAT DO YOU WANT?',q:'What type of opportunities would interest you most?',o:['Starting or growing a business','Jobs and career opportunities','Investments and entrepreneurship','Local community projects','Connecting with people who can help make an idea happen'],m:[{Entrepreneur:3},{Entrepreneur:2,Connector:1},{Entrepreneur:3},{Community:3},{Connector:2,Builder:1}]},
{section:'WHAT DO YOU WANT?',q:'If you had access to the right network of people, what would you most like to accomplish?',o:['Start or grow a business','Build something in my community','Develop an idea','Find new opportunities','Connect with people who share my goals'],m:[{Entrepreneur:2,Builder:1},{Community:3},{Visionary:2,Builder:1},{Entrepreneur:2,Connector:1},{Connector:3}]},
{section:'WHAT WOULD YOU BUILD?',q:'What would you do with $50,000 to make your community better?',o:['Start a business or community initiative','Support education','Improve local infrastructure','Help local families or businesses','Invest in something that creates long-term opportunity','Other'],m:[{Builder:2,Community:1},{Community:3},{Community:3},{Community:2,Builder:1},{Entrepreneur:2,Community:1},{Visionary:1,Builder:1}]},
{section:'WHAT WOULD YOU BUILD?',q:'If you could bring together 100 people to accomplish ONE thing, what would you choose?',o:['Build a business','Solve a problem in my community','Create jobs and opportunities','Support local families and organizations','Build something completely new','Other'],m:[{Entrepreneur:2,Builder:1},{Community:3},{Entrepreneur:2,Community:1},{Community:3},{Visionary:2,Builder:1},{Builder:1}]},
{section:'WHAT WOULD YOU BUILD?',q:'If MagaCircle™ could help you accomplish ONE thing, what would it be?',o:['Build something meaningful','Grow my business','Connect with the right people','Create new opportunities','Make a difference in my community','Turn an idea into reality'],m:[{Builder:2,Community:1},{Entrepreneur:3},{Connector:3},{Entrepreneur:2,Connector:1},{Community:3},{Visionary:2,Builder:1}]}
];
const profiles={Builder:{r:'YOU’RE A BUILDER',i:'⚒',t:'You turn ideas into action.',d:'You see opportunities where others see problems. You want to see something actually happen—and you understand that the right people can make all the difference.',s:'Action • Problem solving • Execution • Getting things done',l:'People, resources, and opportunities that can help turn ideas into reality.'},Connector:{r:'YOU’RE A CONNECTOR',i:'◎',t:'You understand the power of bringing the right people together.',d:'You naturally see relationships and connections that others may overlook. You know great things often begin when the right people find each other.',s:'Relationships • Networking • Collaboration • Bringing people together',l:'People who share your goals and opportunities worth connecting them to.'},Entrepreneur:{r:'YOU’RE AN ENTREPRENEUR',i:'↗',t:'You see opportunity—and you are ready to pursue it.',d:'You are interested in creating, growing, investing, and finding ways to turn opportunity into something bigger.',s:'Opportunity • Business • Innovation • Growth',l:'Business opportunities, resources, investment possibilities, and people who can help you grow.'},Community:{r:'YOU’RE A COMMUNITY BUILDER',i:'⌂',t:'You want to make where you live better.',d:'You are motivated by the idea that people working together can create meaningful improvements in their communities.',s:'Community • Service • Collaboration • Long-term impact',l:'People and resources that can help turn community ideas into action.'},Visionary:{r:'YOU’RE A VISIONARY',i:'✦',t:'You see what could be possible before it exists.',d:'Ideas come naturally to you. What you need is the right people and resources to help bring those ideas to life.',s:'Ideas • Creativity • Innovation • Vision',l:'People who can help turn your vision into something real.'}};
const state={screen:'landing',name:'',email:'',index:0,answers:Array(10).fill(null),referrals:0};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function show(screen){state.screen=screen;$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));window.scrollTo({top:0,behavior:'smooth'});localStorage.setItem('mc_proto',JSON.stringify(state));}
function render(){const q=questions[state.index];$('#counter').textContent=`${state.index+1} / 10`;$('#progress').style.width=((state.index+1)*10)+'%';$('#sectionTitle').textContent=q.section;$('#question').textContent=q.q;const icons=['♟','♧','◎','↗','♡','○'];const box=$('#options');box.innerHTML='';q.o.forEach((txt,i)=>{const b=document.createElement('button');b.className='option'+(state.answers[state.index]===i?' selected':'');b.innerHTML=`<span class="ico">${icons[i]||'○'}</span><span>${txt}</span>`;b.onclick=()=>{state.answers[state.index]=i;render()};box.appendChild(b)});$('#nextBtn').disabled=state.answers[state.index]===null;$('#backBtn').style.visibility=state.index?'visible':'hidden'}
function beginQuiz(){state.index=0;state.answers=Array(10).fill(null);render();show('quiz')}
function profile(){const score={Builder:0,Connector:0,Entrepreneur:0,Community:0,Visionary:0};state.answers.forEach((a,i)=>{if(a!=null)Object.entries(questions[i].m[a]).forEach(([k,v])=>score[k]+=v)});const type=Object.entries(score).sort((a,b)=>b[1]-a[1])[0][0],p=profiles[type];$('#profileRibbon').textContent=p.r;$('#profileIcon').textContent=p.i;$('#profileTitle').textContent=p.t;$('#profileDesc').textContent=p.d;$('#profileStrengths').textContent=p.s;$('#profileLooking').textContent=p.l;show('profile')}
$('#contactForm').onsubmit=e=>{e.preventDefault();state.name=$('#name').value.trim();state.email=$('#email').value.trim();beginQuiz()};$('#nextBtn').onclick=()=>{if(state.answers[state.index]==null)return;if(state.index===2){show('transition3');return}if(state.index===6){show('transition7');return}if(state.index<9){state.index++;render()}else{show('processing');setTimeout(profile,900)}};$('#backBtn').onclick=()=>{if(state.index>0){state.index--;render()}};
document.body.addEventListener('click',e=>{const go=e.target.closest('[data-go]')?.dataset.go,act=e.target.closest('[data-action]')?.dataset.action;if(go)show(go);if(act==='q4'){state.index=3;render();show('quiz')}if(act==='q8'){state.index=7;render();show('quiz')}if(act==='referral')show('referral');if(act==='home'){state.referrals=0;show('landing')}if(act==='share'){ $('#sharePanel').classList.remove('hidden') } if(act==='shareFinal'){ $('#finalShare').innerHTML=document.querySelector('#sharePanel').innerHTML; $('#finalShare').classList.remove('hidden'); }if(act==='simulate'){state.referrals=Math.min(5,state.referrals+1);updateRefs();if(state.referrals===5)setTimeout(()=>show('waitlist'),500)}if(act==='reset'){state.referrals=0;updateRefs()}});
function updateRefs(){$('#refCount').textContent=state.referrals;$$('#dots i').forEach((x,i)=>x.classList.toggle('filled',i<state.referrals))}
function shareText(){return `I’m helping shape MagaCircle™ before launch. Take the 10-question quiz and discover your MagaCircle™ Profile: ${location.href}`}
$$('[data-share]').forEach(b=>b.onclick=async()=>{const kind=b.dataset.share;const text=shareText();if(kind==='copy'){try{await navigator.clipboard.writeText(text);$('#shareStatus').textContent='Invitation copied.'}catch{}}else if(kind==='email'){location.href='mailto:?subject=You’ve been invited to MagaCircle™&body='+encodeURIComponent(text)}else if(kind==='text'){location.href='sms:?&body='+encodeURIComponent(text)}else if(kind==='native'&&navigator.share){navigator.share({title:'MagaCircle™',text,url:location.href})}});
try{const saved=JSON.parse(localStorage.getItem('mc_proto'));if(saved){Object.assign(state,saved);if($('#name'))$('#name').value=state.name||'';if($('#email'))$('#email').value=state.email||'';updateRefs();if(state.screen==='quiz')render();}}catch{}
