const Q=[
{section:'WHO ARE YOU?',tone:'blue',q:'What matters most to you when connecting with other people?',a:['Building genuine relationships','Sharing ideas and experiences','Finding opportunities','Working together toward common goals']},
{section:'WHO ARE YOU?',tone:'blue',q:'How do you naturally contribute to a community?',a:['I come up with ideas','I help people get things done','I share knowledge and resources','I connect people with one another',"I'm more of a supporter or cheerleader"]},
{section:'WHO ARE YOU?',tone:'blue',q:'Which best describes what you\'re looking for right now?',a:['New opportunities','New connections','A way to turn an idea into reality','A community where I belong','Ways to make a difference']},
{section:'WHAT DO YOU WANT?',tone:'green',q:'What do you think is missing most from online communities today?',a:['Authentic connections','Trustworthy information','Opportunities to collaborate','A place where ideas can become action','Communities that actually accomplish things']},
{section:'WHAT DO YOU WANT?',tone:'green',q:'What would you most like MagaCircle™ to help you accomplish?',a:['Meaningful connections','Business opportunities','Knowledge and resources','Collaboration on projects','A platform to share my ideas']},
{section:'WHAT DO YOU WANT?',tone:'green',q:'What type of opportunities would interest you most?',a:['Starting or growing a business','Jobs and career opportunities','Investments and entrepreneurship','Local community projects','Connecting with people who can help make an idea happen']},
{section:'WHAT DO YOU WANT?',tone:'green',q:'If you had access to the right network of people, what would you most like to accomplish?',a:['Start or grow a business','Build something in my community','Develop an idea','Find new opportunities','Connect with people who share my goals']},
{section:'WHAT WOULD YOU BUILD?',tone:'red',q:'What would you do with $50,000 to make your community better?',a:['Start a business or community initiative','Support education','Improve local infrastructure','Help local families or businesses','Invest in something that creates long-term opportunity','Other']},
{section:'WHAT WOULD YOU BUILD?',tone:'red',q:'If you could bring together 100 people to accomplish ONE thing, what would you choose?',a:['Build a business','Solve a problem in my community','Create jobs and opportunities','Support local families and organizations','Build something completely new','Other']},
{section:'WHAT WOULD YOU BUILD?',tone:'red',q:'If MagaCircle™ could help you accomplish ONE thing, what would it be?',a:['Build something meaningful','Grow my business','Connect with the right people','Create new opportunities','Make a difference in my community','Turn an idea into reality']}
];
let state={screen:'landing',q:0,answers:Array(10).fill(null),name:'',email:'',ref:0};
const icons=['👥','💡','🎯','🤝','◌'];
function brand(){return `<div class="brand"><div class="logo"><span class="maga">Maga</span><span class="circle">Circle</span><sup class="tm">™</sup></div><div class="power"><span class="star">★</span> POWER TO THE PEOPLE <span class="star">★</span></div></div>`}
function shell(content,cls=''){document.getElementById('app').innerHTML=`<div class="app"><main class="shell ${cls}">${content}</main></div>`}
function landing(){shell(`<section class="screen hero">${brand()}<div class="content"><h1 class="headline">HELP BUILD<br><span class="red">MAGA</span>CIRCLE™</h1><p class="hero-copy">MagaCircle™ is being built around the people who will use it.</p><p class="hero-copy" style="margin-top:12px">Tell us a little about yourself,<br>what you’re looking for, and<br>what you’d like to accomplish.</p><div class="bullets"><div>10 questions.</div><div>No right or wrong answers.</div></div></div><div class="crowd"><button class="btn red" onclick="go('form')">LET’S BEGIN <span class="arrow">→</span></button></div></section>`,'hero')}
function form(){shell(`<section class="screen form-screen">${brand()}<h1 class="title">FIRST, LET’S<br>GET TO KNOW YOU</h1><label class="label">What’s your name?</label><input id="name" class="field" placeholder="First Name" value="${state.name}"><label class="label">Where should we send your<br>MagaCircle™ launch invitation?</label><input id="email" class="field" type="email" placeholder="Email Address" value="${state.email}"><button class="btn red" onclick="startQuiz()">START THE QUIZ <span class="arrow">→</span></button><p class="privacy">🔒 &nbsp; We’ll use your email to keep<br>you updated about the<br>MagaCircle™ launch.</p></section>`)}
function quiz(){let x=Q[state.q], sel=state.answers[state.q];let pct=((state.q+1)/10)*100;let ans=x.a.map((a,i)=>`<button class="answer ${sel===i?'selected '+x.tone:''}" onclick="pick(${i})"><span class="ico">${icons[i%icons.length]}</span><span>${a}</span>${sel===i?'<span class="check">✓</span>':''}</button>`).join('');shell(`<section class="screen quiz-screen">${brand()}<div class="quiz-head"><div class="count">${state.q+1} / 10</div><div class="progress"><span style="width:${pct}%"></span></div><div class="section-name" style="color:${x.tone==='red'?'#d71920':x.tone==='green'?'#13833a':'#102e74'}">${x.section}</div></div><h1 class="question">${x.q}</h1><div class="answers">${ans}</div><div class="navrow"><button class="back" onclick="back()">← BACK</button><button class="btn ${x.tone==='red'?'red':x.tone==='green'?'green':'navy'}" onclick="nextQ()">CONTINUE <span class="arrow">→</span></button></div></section>`)}
function transition(kind){let after=kind===3?`NOW LET’S TALK ABOUT<br>WHAT YOU WANT.`:`NOW LET’S THINK BIG.`;let copy=kind===3?`You told us a little about who you are.<br>Now let’s explore what you’re looking for—and what you’d like to accomplish.`:`You’ve told us what you’re looking for.<br>Now imagine what you could accomplish with the right people around you.`;shell(`<section class="screen transition ${kind===3?'':'red'}">${brand()}<div class="spacer"></div><div class="circle-icon">${kind===3?'●●':'🚀'}</div><h2>${after}</h2><p>${copy}</p><button class="btn ${kind===3?'navy':'red'}" onclick="resume(${kind})">${kind===3?'CONTINUE':'LET’S GO'} <span class="arrow">→</span></button><div class="spacer"></div></section>`)}
function processing(){shell(`<section class="screen processing">${brand()}<div class="spacer"></div><div class="spinner"></div><h2 style="color:#d71920">ANALYZING YOUR ANSWERS...</h2><ul><li>Connecting the dots...</li><li>Discovering your strengths...</li><li>Building your unique profile...</li><li>Almost there!</li></ul><div class="spacer"></div></section>`)}
function profile(){shell(`<section class="screen profile-screen">${brand()}<div class="profile-card"><h1>YOUR<br>MAGACIRCLE™<br>PROFILE</h1><div class="ribbon">YOU’RE A<br>BUILDER</div><div class="profile-icon">🛠</div><p class="profile-copy">You see opportunities where others see problems. You like turning ideas into action and you understand that the right people can make all the difference.</p><div style="font-size:11px;font-weight:900">YOUR STRENGTHS</div><div class="strengths"><div><b>💡</b>Ideas</div><div><b>✓</b>Action</div><div><b>◎</b>Opportunity</div><div><b>♧</b>Connection</div></div><div style="font-size:11px;font-weight:900;margin-top:12px">WHAT YOU’RE LOOKING FOR</div><div class="looking">Turning ideas into reality</div></div><div class="profile-actions"><button class="btn outline" onclick="go('ref')">NEXT: INVITE 5 PEOPLE →</button></div></section>`)}
function referral(){let dots=[0,1,2,3,4].map(i=>`<span class="dot ${i<state.ref?'on':''}"></span>`).join('');shell(`<section class="screen ref-screen">${brand()}<div class="ref-icon">♙♙</div><h1>YOUR <span class="red">MAGACIRCLE™</span><br>ISN’T COMPLETE YET.</h1><p>MagaCircle™ is built around<br>people connecting with people.</p><p>You just told us what you want<br>to accomplish.</p><p>Now invite the people you think<br>should be part of MagaCircle™.</p><div style="margin-top:14px;font-size:12px;font-weight:900">INVITE 5 PEOPLE</div><div class="ref-count">${state.ref} / 5</div><div class="dots">${dots}</div><button class="btn red" onclick="addRef()">INVITE MY CIRCLE</button><div class="share-note">♧ &nbsp; Share your personal invitation<br>by text, email, or social media.</div></section>`)}
function final(){shell(`<section class="screen final-screen">${brand()}<div class="spacer"></div><h1>YOU’RE IN!</h1><div class="check-big">✓</div><p>You’ve officially secured your place<br>on the MagaCircle™ launch waitlist.</p><h2>WELCOME TO<br>MAGACIRCLE™</h2><p>Thank you for helping shape<br>what MagaCircle™ becomes.<br>We’ll keep you updated as<br>we get closer to launch.</p><div class="final-actions"><button class="btn red" onclick="share()">SHARE MAGACIRCLE™</button><button class="btn outline" onclick="go('landing')">RETURN TO HOME</button></div></section>`)}
function invite(){shell(`<section class="screen invite">${brand()}<div class="confetti">◆　✦　•　◆　✦</div><h1>John invited you to join<br><span class="red">MagaCircle™</span></h1><p>They’re helping shape the platform<br>before launch.</p><p>Take the 10-question quiz and<br>see your MagaCircle™ Profile.</p><button class="btn red" onclick="go('form')">TAKE THE QUIZ <span class="arrow">→</span></button><div class="sharebox"><button onclick="share('Text')"><div class="share-circle">▤</div>Text</button><button onclick="share('Email')"><div class="share-circle">✉</div>Email</button><button onclick="copyLink()"><div class="share-circle">↗</div>Copy Link</button><button onclick="share('Share')"><div class="share-circle">●</div>Share</button></div></section>`)}
function success(){shell(`<section class="screen success">${brand()}<div class="success-icon">✓</div><h1>YOU DID IT!</h1><p>You’ve invited 5 people!</p><p>You’re officially on the<br>MagaCircle™ launch waitlist.</p><h2>WELCOME TO<br>MAGACIRCLE™</h2><button class="btn red" onclick="share()">SHARE MAGACIRCLE™</button></section>`)}
function go(s){state.screen=s;({landing,form,quiz,profile,ref:referral,final,invite,success}[s]||landing)()}
function startQuiz(){state.name=document.getElementById('name').value.trim();state.email=document.getElementById('email').value.trim();if(!state.name||!state.email){alert('Please enter your name and email.');return}state.q=0;go('quiz')}
function pick(i){state.answers[state.q]=i;quiz()}
function nextQ(){if(state.answers[state.q]===null){alert('Please choose an answer.');return}if(state.q===2){transition(3);return}if(state.q===6){transition(7);return}if(state.q<9){state.q++;quiz()}else{processing();setTimeout(profile,1500)}}
function resume(k){state.q=k===3?3:7;quiz()}
function back(){if(state.q>0){state.q--;quiz()}else go('form')}
function addRef(){if(state.ref<5){state.ref++;if(state.ref===5){success();return}referral()}}
function share(label='MagaCircle™'){if(navigator.share){navigator.share({title:'MagaCircle™',text:'I’m helping shape MagaCircle™ before launch.',url:location.href}).catch(()=>{})}else alert('Share MagaCircle™ with your friends!')}
function copyLink(){navigator.clipboard?.writeText(location.href);alert('Invitation link copied!')}
go('landing');
