const questions = [
  {section:'WHO ARE YOU?', q:'What matters most to you when connecting with other people?', options:['Building genuine relationships','Sharing ideas and experiences','Finding opportunities','Working together toward common goals'], map:[{Builder:1,Connector:2},{Visionary:2,Connector:1},{Entrepreneur:2,Connector:1},{Community:1,Builder:2}]},
  {section:'WHO ARE YOU?', q:'How do you naturally contribute to a community?', options:['I come up with ideas','I help people get things done','I share knowledge and resources','I connect people with one another',"I'm more of a supporter or cheerleader"], map:[{Visionary:3},{Builder:3},{Community:2,Builder:1},{Connector:3},{Community:3}]},
  {section:'WHO ARE YOU?', q:'Which best describes what you\'re looking for right now?', options:['New opportunities','New connections','A way to turn an idea into reality','A community where I belong','Ways to make a difference'], map:[{Entrepreneur:2},{Connector:2},{Visionary:1,Builder:2},{Community:3},{Community:2,Builder:1}]},
  {section:'WHAT DO YOU WANT?', q:'What do you think is missing most from online communities today?', options:['Authentic connections','Trustworthy information','Opportunities to collaborate','A place where ideas can become action','Communities that actually accomplish things'], map:[{Connector:2},{Community:2},{Connector:1,Builder:1},{Visionary:1,Builder:2},{Community:2,Builder:1}]},
  {section:'WHAT DO YOU WANT?', q:'What would you most like MagaCircle™ to help you accomplish?', options:['Meaningful connections','Business opportunities','Knowledge and resources','Collaboration on projects','A platform to share my ideas'], map:[{Connector:3},{Entrepreneur:3},{Community:2},{Builder:2,Connector:1},{Visionary:3}]},
  {section:'WHAT DO YOU WANT?', q:'What type of opportunities would interest you most?', options:['Starting or growing a business','Jobs and career opportunities','Investments and entrepreneurship','Local community projects','Connecting with people who can help make an idea happen'], map:[{Entrepreneur:3},{Entrepreneur:2,Connector:1},{Entrepreneur:3},{Community:3},{Connector:2,Builder:1}]},
  {section:'WHAT DO YOU WANT?', q:'If you had access to the right network of people, what would you most like to accomplish?', options:['Start or grow a business','Build something in my community','Develop an idea','Find new opportunities','Connect with people who share my goals'], map:[{Entrepreneur:2,Builder:1},{Community:3},{Visionary:2,Builder:1},{Entrepreneur:2,Connector:1},{Connector:3}]},
  {section:'WHAT WOULD YOU BUILD?', q:'What would you do with $50,000 to make your community better?', options:['Start a business or community initiative','Support education','Improve local infrastructure','Help local families or businesses','Invest in something that creates long-term opportunity','Other'], map:[{Builder:2,Community:1},{Community:3},{Community:3},{Community:2,Builder:1},{Entrepreneur:2,Community:1},{Visionary:1,Builder:1}]},
  {section:'WHAT WOULD YOU BUILD?', q:'If you could bring together 100 people to accomplish ONE thing, what would you choose?', options:['Build a business','Solve a problem in my community','Create jobs and opportunities','Support local families and organizations','Build something completely new','Other'], map:[{Entrepreneur:2,Builder:1},{Community:3},{Entrepreneur:2,Community:1},{Community:3},{Visionary:2,Builder:1},{Builder:1}]},
  {section:'WHAT WOULD YOU BUILD?', q:'If MagaCircle™ could help you accomplish ONE thing, what would it be?', options:['Build something meaningful','Grow my business','Connect with the right people','Create new opportunities','Make a difference in my community','Turn an idea into reality'], map:[{Builder:2,Community:1},{Entrepreneur:3},{Connector:3},{Entrepreneur:2,Connector:1},{Community:3},{Visionary:2,Builder:1}]}
];

const profiles = {
  Builder:{icon:'🔨', ribbon:"YOU'RE A BUILDER", title:'You turn ideas into action.', description:"You aren't satisfied with simply talking about what could be done. You want to see something actually happen—and you understand that the right people can make all the difference.", strengths:'Action • Problem solving • Execution • Getting things done', looking:'People, resources, and opportunities that can help turn ideas into reality.', help:'Connect with the people, resources, and opportunities that can help turn your ideas into action.'},
  Connector:{icon:'🔗', ribbon:"YOU'RE A CONNECTOR", title:'You understand the power of bringing the right people together.', description:'You naturally see relationships and connections that others may overlook. You know that great things often begin when the right people find each other.', strengths:'Relationships • Networking • Collaboration • Bringing people together', looking:'People who share your goals and opportunities worth connecting them to.', help:'Discover people, projects, and opportunities where your ability to connect can create momentum.'},
  Entrepreneur:{icon:'🚀', ribbon:"YOU'RE AN ENTREPRENEUR", title:'You see opportunity—and you are ready to pursue it.', description:'You are interested in creating, growing, investing, and finding ways to turn opportunity into something bigger.', strengths:'Opportunity • Business • Innovation • Growth', looking:'Business opportunities, resources, investment possibilities, and people who can help you grow.', help:'Find connections, resources, and opportunities that can help move your next venture forward.'},
  Community:{icon:'🌎', ribbon:"YOU'RE A COMMUNITY BUILDER", title:'You want to make where you live better.', description:'You are motivated by the idea that people working together can create meaningful improvements in their communities.', strengths:'Community • Service • Collaboration • Long-term impact', looking:'People and resources that can help turn community ideas into action.', help:'Connect with people and resources that can help turn community ideas into measurable action.'},
  Visionary:{icon:'💡', ribbon:"YOU'RE A VISIONARY", title:'You see what could be possible before it exists.', description:'Ideas come naturally to you. What you need is the right people and resources to help bring those ideas to life.', strengths:'Ideas • Creativity • Innovation • Vision', looking:'People who can help turn your vision into something real.', help:'Find collaborators and resources that can help transform your strongest ideas into reality.'}
};

const state={screen:'landing',name:'',email:'',index:0,answers:Array(10).fill(null),referrals:0,scores:{Builder:0,Connector:0,Entrepreneur:0,Community:0,Visionary:0},profile:null};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function journeyStep(){if(state.screen==='landing')return 1;if(state.screen==='contact')return 2;if(state.screen==='quiz'||state.screen==='transition3')return state.index<=2?3:state.index<=6?4:5;if(state.screen==='processing'||state.screen==='profile')return 6;if(state.screen==='referral')return 7;if(state.screen==='waitlist')return 8;return 1;}
function show(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));state.screen=name;const j=journeyStep();$$('[data-journey]').forEach(el=>{const n=Number(el.dataset.journey);el.classList.toggle('active',n===j);el.classList.toggle('done',n<j)});window.scrollTo({top:0,behavior:'smooth'});}
function save(){localStorage.setItem('magacircle_v1_1',JSON.stringify(state));}
function load(){try{const x=JSON.parse(localStorage.getItem('magacircle_v1_1'));if(x){Object.assign(state,x);}}catch(e){}}
function renderQuestion(){const x=questions[state.index];$('#questionCounter').textContent=`${state.index+1} / 10`;$('#progressFill').style.width=`${(state.index+1)*10}%`;$('#sectionLabel').textContent=x.section;$('#questionText').textContent=x.q;const wrap=$('#options');wrap.innerHTML='';x.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option'+(state.answers[state.index]===i?' selected':'');b.innerHTML=`<span class="opt-icon">${['●','◌','✦','◆','♥','○'][i]||'○'}</span><span>${o}</span>`;b.addEventListener('click',()=>{state.answers[state.index]=i;renderQuestion();save();});wrap.appendChild(b)});$('#continueBtn').disabled=state.answers[state.index]===null;$('#backBtn').style.visibility=state.index===0?'hidden':'visible';}
function startQuiz(){show('contact');}
function beginQuiz(){state.index=0;state.answers=Array(10).fill(null);renderQuestion();show('quiz');save();}
function next(){if(state.answers[state.index]===null)return;if(state.index===2){show('transition3');return;}if(state.index===6){show('transition7');return;}if(state.index<9){state.index++;renderQuestion();save();}else{show('processing');setTimeout(buildProfile,1100);}}
function resumeFromTransition(target){state.index=target;renderQuestion();show('quiz');save();}
function buildProfile(){state.scores={Builder:0,Connector:0,Entrepreneur:0,Community:0,Visionary:0};state.answers.forEach((a,i)=>{if(a===null)return;Object.entries(questions[i].map[a]).forEach(([k,v])=>state.scores[k]+=v)});const sorted=Object.entries(state.scores).sort((a,b)=>b[1]-a[1]);state.profile=sorted[0][0];const p=profiles[state.profile];$('#profileIcon').textContent=p.icon;$('#profileRibbon').textContent=p.ribbon;$('#profileTitle').textContent=p.title;$('#profileDescription').textContent=p.description;$('#profileStrengths').textContent=p.strengths;$('#profileLooking').textContent=p.looking;$('#profileHelp').textContent=p.help;show('profile');save();}
function referralRender(){const n=Math.min(5,state.referrals);$('#refCount').textContent=n;$('#refDots').querySelectorAll('span').forEach((d,i)=>d.classList.toggle('filled',i<n));if(n>=5){setTimeout(()=>show('waitlist'),350);}save();}
function shareText(){return `I've been helping shape MagaCircle™ before launch. Take the 10-question quiz and discover your MagaCircle™ Profile: ${location.href}`}
async function share(kind){const url=location.href;const text=shareText();if(kind==='copy'){try{await navigator.clipboard.writeText(text);$('#shareStatus').textContent='Invitation copied to your clipboard.';}catch(e){$('#shareStatus').textContent='Copy is unavailable in this browser—use the Share option instead.'}}else if(kind==='native'&&navigator.share){try{await navigator.share({title:'MagaCircle™',text,url})}catch(e){}}else if(kind==='text'){location.href=`sms:?&body=${encodeURIComponent(text)}`;}else if(kind==='email'){location.href=`mailto:?subject=${encodeURIComponent('Join me on MagaCircle™')}&body=${encodeURIComponent(text)}`;}else{$('#shareStatus').textContent='Choose a sharing option above.';}}
function reset(){localStorage.removeItem('magacircle_v1_1');location.reload();}
function showFinalShare(){const p=$('#finalSharePanel');p.innerHTML=`<button class="share-btn" data-share="text">💬<span>TEXT</span></button><button class="share-btn" data-share="email">✉️<span>EMAIL</span></button><button class="share-btn" data-share="copy">🔗<span>COPY LINK</span></button><button class="share-btn" data-share="native">↗️<span>SHARE</span></button>`;p.classList.remove('hidden');p.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>share(b.dataset.share));}

$('#contactForm').addEventListener('submit',e=>{e.preventDefault();state.name=$('#name').value.trim();state.email=$('#email').value.trim();beginQuiz();});
$('#continueBtn').addEventListener('click',next);$('#backBtn').addEventListener('click',()=>{if(state.index>0){state.index--;renderQuestion();save();}});
$$('[data-action="begin"]').forEach(b=>b.onclick=startQuiz);$$('[data-action="toQuiz4"]').forEach(b=>b.onclick=()=>resumeFromTransition(3));$$('[data-action="toQuiz8"]').forEach(b=>b.onclick=()=>resumeFromTransition(7));$$('[data-action="toReferral"]').forEach(b=>b.onclick=()=>{ $('#referralGreeting').textContent=`${state.name}, help build MagaCircle™.`;referralRender();show('referral');});$$('[data-action="showShare"]').forEach(b=>b.onclick=()=>$('#sharePanel').classList.toggle('hidden'));$$('[data-action="testReferral"]').forEach(b=>b.onclick=()=>{if(state.referrals<5){state.referrals++;referralRender();}});$$('[data-action="resetReferrals"]').forEach(b=>b.onclick=()=>{state.referrals=0;referralRender();});$$('[data-share]').forEach(b=>b.onclick=()=>share(b.dataset.share));$$('[data-action="showShareAgain"]').forEach(b=>b.onclick=showFinalShare);$$('[data-action="home"]').forEach(b=>b.onclick=reset);
load();
if(state.name){$('#name').value=state.name;$('#email').value=state.email;}
if(state.screen==='quiz'){renderQuestion();show('quiz')}else if(state.screen==='profile'&&state.profile){buildProfile()}else if(state.screen==='referral'){referralRender();$('#referralGreeting').textContent=`${state.name||'Your'}, help build MagaCircle™.`;show('referral')}else if(state.screen==='waitlist'){show('waitlist')}
